on: [push, pull_request]
name: Test
jobs:
  osstest:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      DRIVER: oss
    steps:
      - name: start minlo
        run: docker run -p 9000:9000 -p 9001:9001 -e "MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE" -e "MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" -d quay.io/minio/minio server /data --console-address ":9001"
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test -v --v -tags="alltest osstest"

  hybriddbtest:
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    env:
      DRIVER: hybriddb
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test -v --v -tags alltest

#  ipfstest:
#    strategy:
#      matrix:
#        go-version: [ 1.16.x ]
#        os: [ ubuntu-latest, macos-latest, windows-latest ]
#    runs-on: ${{ matrix.os }}
#    env:
#      DRIVER: ipfs
#    steps:
#      - name: Install Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: ${{ matrix.go-version }}
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Test
#        run: go test -v --v -tags alltest

#  orbitdbtest:
#    strategy:
#      matrix:
#        go-version: [ 1.16.x ]
#        os: [ ubuntu-latest, macos-latest, windows-latest ]
#    runs-on: ${{ matrix.os }}
#    env:
#      DRIVER: orbitdb
#    steps:
#      - name: Install Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: ${{ matrix.go-version }}
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Test
#        run: go test -v --v -tags alltest

  goleveldbtest:
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    env:
      DRIVER: goleveldb
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test -v --v -tags alltest
